"""sync_orm_with_db

Revision ID: 4360c4ea5ae3
Revises: 
Create Date: 2026-07-13 14:12:50.821279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4360c4ea5ae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除没有依赖的表
    op.drop_index(op.f('ix_sop_checkpoints_expires_at'), table_name='sop_checkpoints')
    op.drop_index(op.f('ix_sop_checkpoints_pipeline_run_id'), table_name='sop_checkpoints')
    op.drop_index(op.f('ix_sop_checkpoints_sop_id'), table_name='sop_checkpoints')
    op.drop_index(op.f('ix_sop_checkpoints_thread_id'), table_name='sop_checkpoints')
    op.drop_table('sop_checkpoints')
    # 按 FK 依赖顺序删除：子表先删，父表后删
    # plan_task_logs → plan_task_instances，所以先删 logs
    op.drop_index(op.f('idx_ptl_instance'), table_name='plan_task_logs')
    op.drop_index(op.f('ix_plan_task_logs_instance_id'), table_name='plan_task_logs')
    op.drop_table('plan_task_logs')
    # plan_task_deliverables → plan_task_instances，在 instances 前删
    op.drop_index(op.f('idx_ptd_submitted'), table_name='plan_task_deliverables')
    op.drop_index(op.f('ix_plan_task_deliverables_instance_id'), table_name='plan_task_deliverables')
    op.drop_table('plan_task_deliverables')
    # plan_task_instances → plan_task_templates，在 templates 前删
    op.drop_index(op.f('idx_pti_executor_status'), table_name='plan_task_instances')
    op.drop_index(op.f('idx_pti_llm_failed'), table_name='plan_task_instances')
    op.drop_index(op.f('idx_pti_project'), table_name='plan_task_instances')
    op.drop_index(op.f('idx_pti_status_deadline'), table_name='plan_task_instances')
    op.drop_index(op.f('idx_pti_unscheduled'), table_name='plan_task_instances')
    op.drop_index(op.f('uq_pti_period'), table_name='plan_task_instances', postgresql_where="((status)::text <> 'CANCELLED'::text)")
    op.drop_table('plan_task_instances')
    # plan_task_templates 最后删
    op.drop_index(op.f('idx_ptt_status_type'), table_name='plan_task_templates')
    op.drop_table('plan_task_templates')
    op.alter_column('company_info', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment='是否管理单位（建设单位/代建单位）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('files', 'file_category',
               existing_type=sa.VARCHAR(length=50),
               comment='文件业务分类：PROJECT_LICENSE/CONTRACT/WORK_RECORD/PHASE_DELIVERABLE/PROCESS_DOC/MANAGEMENT_SPEC/OTHER',
               existing_nullable=True,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.drop_index(op.f('idx_files_category'), table_name='files')
    op.alter_column('project_nodes', 'visibility_mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False,
               comment='文件可见模式：specific（按 node_accessible_files 绑定）/ all_project_files（全项目文件默认可见）',
               existing_server_default=sa.text("'public'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_nodes', 'visibility_mode',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='文件可见模式：specific（按 node_accessible_files 绑定）/ all_project_files（全项目文件默认可见）',
               existing_server_default=sa.text("'public'::character varying"))
    op.create_index(op.f('idx_files_category'), 'files', ['file_category'], unique=False)
    op.alter_column('files', 'file_category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='文件业务分类：PROJECT_LICENSE/CONTRACT/WORK_RECORD/PHASE_DELIVERABLE/PROCESS_DOC/MANAGEMENT_SPEC/OTHER',
               existing_nullable=True,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.alter_column('company_info', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否管理单位（建设单位/代建单位）',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('plan_task_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['plan_task_instances.id'], name=op.f('plan_task_logs_instance_id_fkey')),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('plan_task_logs_operator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_task_logs_pkey'))
    )
    op.create_index(op.f('ix_plan_task_logs_instance_id'), 'plan_task_logs', ['instance_id'], unique=False)
    op.create_index(op.f('idx_ptl_instance'), 'plan_task_logs', ['instance_id', 'created_at'], unique=False)
    op.create_table('plan_task_templates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('initiator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('executor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('deadline_rule', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('verification_standard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workflow_definition_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_calculation_failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_failure_notified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('plan_task_templates_creator_id_fkey')),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name=op.f('plan_task_templates_executor_id_fkey')),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name=op.f('plan_task_templates_initiator_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('plan_task_templates_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_task_templates_pkey')),
    sa.UniqueConstraint('template_no', name=op.f('plan_task_templates_template_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ptt_status_type'), 'plan_task_templates', ['status', 'task_type'], unique=False)
    op.create_table('plan_task_instances',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instance_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('period_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('initiator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('executor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phase_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('deadline_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reminded_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('escalated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('original_executor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('escalation_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_standard', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('submitted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('archived_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workflow_instance_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_unscheduled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('anomaly_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('llm_calculation_failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_failure_notified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name=op.f('plan_task_instances_executor_id_fkey')),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name=op.f('plan_task_instances_initiator_id_fkey')),
    sa.ForeignKeyConstraint(['original_executor_id'], ['users.id'], name=op.f('plan_task_instances_original_executor_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('plan_task_instances_project_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['plan_task_templates.id'], name=op.f('plan_task_instances_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_task_instances_pkey')),
    sa.UniqueConstraint('instance_no', name=op.f('plan_task_instances_instance_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('uq_pti_period'), 'plan_task_instances', ['template_id', 'period_key'], unique=True, postgresql_where="((status)::text <> 'CANCELLED'::text)")
    op.create_index(op.f('idx_pti_unscheduled'), 'plan_task_instances', ['is_unscheduled', 'created_at'], unique=False)
    op.create_index(op.f('idx_pti_status_deadline'), 'plan_task_instances', ['status', 'deadline_at'], unique=False)
    op.create_index(op.f('idx_pti_project'), 'plan_task_instances', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_pti_llm_failed'), 'plan_task_instances', ['llm_calculation_failed', 'llm_failure_notified'], unique=False)
    op.create_index(op.f('idx_pti_executor_status'), 'plan_task_instances', ['executor_id', 'status'], unique=False)
    op.create_table('plan_task_deliverables',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_acceptance_check', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['plan_task_instances.id'], name=op.f('plan_task_deliverables_instance_id_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('plan_task_deliverables_submitted_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_task_deliverables_pkey'))
    )
    op.create_index(op.f('ix_plan_task_deliverables_instance_id'), 'plan_task_deliverables', ['instance_id'], unique=False)
    op.create_index(op.f('idx_ptd_submitted'), 'plan_task_deliverables', ['submitted_by', 'submitted_at'], unique=False)
    op.create_table('sop_checkpoints',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sop_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmed_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resumed_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confirm_keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cancel_keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sop_checkpoints_pkey'))
    )
    op.create_index(op.f('ix_sop_checkpoints_thread_id'), 'sop_checkpoints', ['thread_id'], unique=False)
    op.create_index(op.f('ix_sop_checkpoints_sop_id'), 'sop_checkpoints', ['sop_id'], unique=False)
    op.create_index(op.f('ix_sop_checkpoints_pipeline_run_id'), 'sop_checkpoints', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_sop_checkpoints_expires_at'), 'sop_checkpoints', ['expires_at'], unique=False)
    # ### end Alembic commands ###
